export default {

  myBuddy: "MyBuddy",
  welcome: "Welcome",
form: {
  error: {
    baduser: "Unknown user",
    bademail: "Invalid email",
    badpwd: "Incorrect password",
    badpassword: "Invalid password",
    badcode: "Incorrect code",
    badfirstname: "Invalid first name",
    badlastname: "Invalid last name",
    badterms: "Invalid terms",
    badattempt: "Incorrect attempt",
    isuseralready: "This user already exists",
    error: "Error",
    errorBackend: "Server error",
  },
  success: "Success",
  done: "Information has been saved",
},

auth: {
  errors: {
    baduser: "Unknown user",
    bademail: "Invalid email",
    badpwd: "Incorrect password",
    badpassword: "Invalid password",
    badcode: "Incorrect code",
    badfirstname: "Invalid first name",
    badlastname: "Invalid last name",
    badterms: "Invalid terms",
    badattempt: "Incorrect attempt",
    isuseralready: "This user already exists",
    error: "Error",
  },
  logout: "Log Out",
  login: {
    login: "Login",
    submit: "Submit",
    button: "Sign In",
    password: "Password",
    title: "Login to BuddyDiary",
    noAccount: "No account yet?",
    forgot: {
      title: "Forgot your password?",
      button: "Retrieve it here",
    },
  },
  signup: {
    timeToComplete: "It's time to create your account. Fill in all the required fields.",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    emailConf: "Email Confirmation",
    button: "Sign Up",
    title: "Create an Account",
    login: "Already have an account?",
    terms:
      "By continuing your registration, you agree \n to our general terms of use",
    learn: "Learn more",
  },
  forgot: {
    title: "Forgot Password",
    resetpwd: "Reset Password",
    button: "Send",
    submit: "Submit",
    errormail: "Email not found!",
    text: "Enter your email address and receive a code to set a new password.",
  },
  verifyCode: {
    verifyCode: "Verify the code you received by email",
    headerTxt: "We have sent an email",
    lineTxt:
      "We have sent a temporary verification code to your inbox. Paste it into the field below.",
    button: "Verify Code",
    title: "Code Verification",
    inputText: "Verification Code",
  },
  setPassword: {
    title: "Set Password",
    infos: "Final steps for account creation. Save your password.",
    maxChar: "At least 8 characters",
    upperChar: "1 uppercase letter",
    specialChar: "1 special character",
    setPassword: "Set Password",
    button: "Complete Registration",
    password: "New Password",
    passwordConf: "Confirm New Password",
    completeRegister: "Your registration is complete",
    completeChangePwd: "Your password has been successfully changed",
    validation: "Success",
  },
},

dashboard: {
  title: "Dashboard",
  welcome: "Welcome",
  feeds: "This is your dashboard. You can get a quick overview of the latest BE MY GUEST feeds.",
  activeNotifications: "Enable Notifications",
  newMessage: "New message received",
  completeProfil: "Complete your profile",
},

permission: {
  title: "Request for permission to use the camera",
  accept: "Accept",
},

mission: {
  title: "Mission",
},

message: {
  title: "Inbox",
},

welcome: {
  welcomeText: "You can create one or more profiles, exchange tips, advice, and tricks with other owners. Find a breeder, professional, or pet service. And meet other pets near you.",
  WelcomeAnimalMiss: "But first, you need to create a profile, choose ...",
  chooseProfil: "Choose your profile",
  gotAnimal: "Do you own one or more pets?",
  noGotAnimal: "Are you looking to adopt a pet?",
  professionalAnimal: "Are you a pet professional?",
},


  profile : {
    title : 'Profile',
    welcome: "Welcome",
    logOut: "Log out",
    chooseProfile: "Your profils",
    adoption: "Adoption",
    animal: "Animal",
    society: "Companies",
  },

  wall: {
    title: 'WallScreen',
    unvalidAppVersion: "Your version is no longer compatible. An update is required for the application to work properly.",
    newVersion: "Install the new version",
  },
  
  userStatus: {
    chooseProfil: "Choose your profile",
    Got_Animal: "You own one or more animals",
    NoGot_Animal: "You are looking to adopt an animal",
    professionalAnimal: "You are a professional in the animal sector. Health, Breeding, Associations, Shelters",
  },
  species: {
    title: "Species",
    search: "Search ...",
    chooseSpecies: "Choose a species",
  },
  breeds: {
    title: "Breeds",
  },
  countries: {
    title: "Countries",
  },

  animalProfile: {
  gender: "Gender",
  years: "Years",
  buddies: "Buddies",
  followers: "Followers",
  privateProfile: "Private Profile",
  informations: "Information",
  obligatory: "Required",
  title: "Profile",
  name: "Name",
  man: "Male",
  woman: "Female",
  other: "Other",
  firstName: "First Name",
  fname: "First Name / Username / Company",
  birthday: "Date of Birth",
  submit: "Submit",
  height: "Height",
  weight: "Weight",
  sociability: "Sociability",
  sterilisation: "Sterilized",
  noSterilisation: "",
  small: "Small",
  average: "Medium",
  tall: "Tall",
  lof: "Certificates and Documents",
  reproduction: "Breeding",
  adoption: "For Adoption",
  description: "Description",
  searchDescription: "Specify your search",
  prosDescription: "What is your activity?",
  dynamic: "Dynamic",
  player: "Playful",
  adoptionTitle: "You are looking to adopt",
  adoptionName: "Are you a private individual, association, or professional?",
  yourSearch: "You are searching for",
  private: "Invisible Account",
  dd: "DD",
  mm: "MM",
  aaaa: "YYYY",
  map: "Visible on the map?",
  love: "Visible on LoveSwap?",
  allowGeoloc: "Geolocation:",
  email: "Email",
  country: "Country",
  town: "City",
  zipCode: "Postal Code",
  adress: "Address",
},

addPicture: {
  title: "Add Image",
},

fullScreenVideo: {
  title: "Full Screen Video",
  confirm: "The media has been saved to your library.",
  close: "Close",
},
  videoScreen: {
    title: "Video",
},

medias: {
  title: "Add Media",
  saveToLibrary: "Save to Library",
  videos: "Videos",
  camera: "Camera",
  modify_profil: "Add an image from ...",
  library: "Gallery",
  download: "Download from:",
  takePicture: "Take a picture",
  takeVideo: "Record a video",
  postVideo: "Post the video",
  got_Animal: "You own one or more pets ...",
  noGot_Animal: "You are looking to adopt or you are a pet professional. Health, Breeding, Associations, Shelters ...",
  share_Video: "Share this video",
  videoProcessing: "Depending on your connection quality and video type, processing may take some time.",
  pleaseWait: "Video is being processed ... Please wait",
},

profiles: {
  title: "Your Profiles",
  male: "Male",
  female: "Female",
  other: "Other",
  localisation: "Location",
},

addPost: {
  title: "New Post",
  editPost: "Edit Post",
  addLegend: "Add a caption ...",
  publish: "Share",
  mediaTraitment: "Processing media",
},

legends: {
  title: "Legends",
},
signalment: {
    title: "Signalement",
},
  addComment: {
  title: "Comments",
  answer: "Reply...",
  addFollower: "Follow",
  removeFollower: "Unfollow",
  liked: "Like",
  delete: "Delete",
  commentary: "Comment(s)",
  addComments: "Add",
  modify: "Edit",
  publish: "Publish",
  response: "In response to ",
  tendancyResponse: "Trending responses",
},

loveSwap: {
  noMoreCards: "No more cards",
  like: "Like",
  noLike: "Dislike",
  yes: "Yes",
  no: "No",
  loveMatch: "LoveMatch",
  likers: "Likers",
  searchSwapDistance: "Choose search distance",
  all: "All genders",
  allSpeciesSearch: "All species",
  allBreedsSearch: "All breeds",
  specifySearch: "Specify your search:",
  loveNewSearch: "New search",
  reproduction: "Breeding",
  adoption: "Adoption",
  undo: "Undo",
  chooseSpecies: "Choose species",
  chooseBreeds: "Choose breeds",
  search: "Search"
},

premium: {
  title: "Premium Account",
  activate: "Activate your Premium Account",
},

loveMatch: {
  title: "Your Matches",
  matches: "Matches",
  myLikers: "They liked you",
  myLovers: "Your Matches",
},

loveLikers: {
  title: "Love Likers",
},

animalDetails: {
  title: "Animal Details",
  posts: "Posts",
  followers: "Followers",
},

postList: {
  title: "Post List",
},

likerList: {
  title: "Liker List",
},

friendList: {
  title: "Friend List",
},

followerList: {
  title: "Follower List",
},

favoriteList: {
  title: "Favorite List",
},

bookmarksList: {
  title: "Bookmarks List",
},

modalSettings: {
  switchProfile: "Switch / Delete / Add",
  profile: "Profile",
  addProfile: "Add a profile",
  buddies: "Buddies",
  likes: "Likes",
  blockedMembers: "Blocked members",
  settings: "Settings",
  legals: "Legals",
  logOut: "Log Out",
  geolocalisation: "Geolocation",
  activeGeolocalisation: "Enable geolocation",
  notifications: "Notifications",
  favorite: "Favorite posts",
  userSettings: "User Settings",
  alert: "Lost or stolen animal alert"
},

sharePost: {
  title: "Share Post",
},

sendPost: {
  title: "Share a Post",
},

chatMessage: {
  title: "Chat Message",
},

chatRoom: {
  title: "Add Message",
},

notifications: {
  title: "Notifications",
  AllowNotificationTxt: "Allow notifications and receive messages from other members.",
  activeNotifications: "Enable notifications",
},

logOut: {
  title: "Log Out",
  seeYouSoon: "See you soon...",
},

legal: {
  title: "Legal Agreement",
},

  Medias: {
  SaveToLibrary: "Save to Library",
  Videos: "Videos",
  Camera: "Camera",
  Modify_profil: "Add a picture from ...",
  Library: "Media Gallery",
  Download: "Download from:",
  takepicture: "Take a picture",
  Takevideo: "Record a new video",
  PostVideo: "Post the video",
  sendVideo: "Use the video",
  Got_Animal: "You own one or more pets ...",
  NoGot_Animal: "You are looking to adopt or you are a pet professional. Health, Breeding, Associations, Shelters ...",
  Share_Video: "Share this video",
  VideoProcessing: "Depending on your connection quality and the type of video, processing may take some time.",
  PleaseWait: "Video is being processed ... Please wait",
},

messages: {
  deletedRoom: "This conversation has been deleted",
},

user: {
  searchAdopt: "Looking to adopt:",
  noPosts: "There are no posts",
  published: "Posts",
},

marker: {
  selectMarker: "Choose a marker type",
  update: "Update",
  title: "Markers list",
  details: "Marker details",
},

bloker: {
  title: "Blocked profiles",
  unblock: "Unblock",
},
userSetting: {
  title: "User Settings",
  changeEmail: "Change Email",
  changePwd: "Change Password",
  deleteAccount: "Delete Account",
  isPremium: "Premium Account",
  changeEmailTxt: "To change your email, please enter your current email. You will receive a code required to update your address.",
  newAdress: "New Email Address",
  confirmEmail: "Confirm New Email",
  accountInformations: "Account Information",
  gender: "Your Gender",
  country: "Your Country?",
  search: "Search",
  userUpdated: "Your settings have been successfully updated.",
  actualEmail: "Current Email",
  newEmail: "New Email",
  confirmNewEmail: "Confirm New Email",
  alreadyExist: "This address already exists",
  error: "Error",
  newPwd: "New Password",
  newPwdConfirm: "Confirm New Password",
},
alert:{
  addPicture: "Add photos",
  title: "Alert, request for help",
  alertSubject: "Do you want to activate the alert and see on the wall a drop-down menu corresponding to your alert within 20km",

},
launchAlert:{
  title: "Information",
  alertSubject: "Do you want to activate the alert and see on the wall a drop-down menu corresponding to your alert within 20km",
  alertPinPlace : "Point on the map to the place where your pet has disappeared, been stolen, or the risk areas.\n",
  alertPinPCancel : "Cancel with ",
  savePinAlert : "Save it with ",
  contact: "Contact the owner",
  informations: "You will define from a central point an alert zone for all BuddyDiary users.",
},

alertDetails: {
  title: "Alert Details",
  lost: "Lost",
  stolen: "Stolen",
  hurted: "Injured",
  poisonned: "Poisoned",
  subject: "You are about to launch a general alert for all MyBuddy users within a 50km radius.\n\nPlease fill in the following fields.",
  alertType: "Define your alert for",
  textTooLong: "You have exceeded the text limit.",
  warning: "Warning",
  addImage: "Add recent photos",
  maxAlert: "You have exceeded the number of available alerts. Upgrade to Premium mode to add more alerts.",
},
alertList: {
title: "Your alerts",
},



  Page: {
  Male: "Male",
  Female: "Female",
  Adoption: "Adoption",
  Active_Premium: "You must activate your Premium account to use Loveswap.",
  Nomore_Cards: "There are no profiles matching your search. \n \n View likers?",
  Health_Place: "My pet’s health",
  Alert_Lost: "Alert, I lost my pet",
  Market_Place: "Marketplace",
  My_Blokers: "Blocked members",
  My_Likes: "My likes",
  Download: "Download",
  Downloading: "Loading...",
  Markerpin_1: "Place your marker on the map. Cancel with ",
  Markerpin_2: "Save it with ",
  Other_Animals: "Other animals",
  All_Animals: "All animals",
  Answer: "Reply",
  Animal_Create_Profile: "New profile",
  Visitor_Create_Profile: "Profile",
  Mentions_Legals: "Legal notices",
  Member_Date: "Member since",
  Premium_Member_Date: "Premium member since",
  Block_Member: "Block",
  Member_No: "This profile has been deleted",
  Subscriptions: "Buddies",
  Blokers: "Blocked members",
  My_Subscriptions: "My buddies",
  Subscribers: "Buddies",
  Abonned: "Followers",
  NoLoveLikerList: "Unselected profiles",
  Marker_Detail: "Marker",
  Marker_List: "Markers list",
  Add_Friends: "Add as buddy",
  Delete_Friend: "Remove",
  Day: "Day",
  Month: "Month",
  Year: "Year",
  General_settings: "Settings",
  Legends: "Legends",
  Loading: "Loading...",
  Posts: "Posts",
  Followers: "Followers",
  Follow: "Follow",
  Store: "Shops",
  Health: "Health",
  Services: "Services",
  Outdoor: "Outdoor",
  Comments: "Comments",
  Add_Comments: "Add comment",
  Answer_Comments: "Reply...",
  Commentary: "Comment(s)",
  Add_Commentary: "Comments",
  Add_Message: "Send message",
  Add_Typeof: "Add species",
  Add_Breed_Txt: "You can add a breed + if it is not in the list...",
  Publish: "Publish",
  Modify: "Edit",
  Member_Since: "Member since",
  Liked: "Liked",
  Liked_by: "Liked by",
  Animal_Details: "Identity",
  Animals_Map: "Map",
  Swap_Fiancy: "Love swap",
  Seefriends: "Followers",
  SeePostfriends: "Friends",
  SeeLegends: "Icon legends",
  Signalment: "Report",
  Marker_Signalment: "Marker report",
  My_Friends: "My buddies",
  Post_Likers: "Likers",
  Settings: "Settings",
  AnimalsMap: "Animals map",
  Next: "Next",
  Validate: "Validate",
  Add: "Add",
  Animal_Profile: "Edit profile",
  BreedScreen: "Breed",
  Add_Animal: "Add animal",
  Create_New_Animal: "Add a new animal",
  List_Animal: "Profiles",
  Create_Profil: "Create profile",
  Add_BreedScreen: "Add new breed",
  Add_BreedScreenTxt: "Add your pet’s breed...",
  SpeciesScreen: "Species",
  Choose_Town: "Your city",
  Privatie: "Private",
  Age: "Years",
  No_Profil: "Complete the profile...",
  Account: "Account",
  Delete_Account: "Delete my account",
  Delete_Account_Txt: "All your messages and data will be permanently deleted...",
  Accept_Legals: "You acknowledge having read and accepted our privacy policy",
  Delete: "Delete",
  Just_Now: "Just now...",
  Your_Account: "Your account",
  Choose_Profil: "Choose profile",
  Choose_Typeof: "Choose species",
  Change_Profil: "Change profile",
  See_Profile: "View profile",
  User_Profile: "Your profile",
  Password: "Password",
  Soon_Available: "Coming soon...",
  LoveMessage: "Messages",
  Publicity: "Advertisement",
  Notifications: "Notifications",
  Premium_Status: "Premium account",
  Geolocalisation: "Geolocation",
  Log_Out: "Logout",
  SeeYouSoon: "See you soon...",
  Send: "Send",
  Placeholder_Youressage: "Your message...",
  Chat_Screen: "Chat screen",
  Profile: "Profile",
  New_Profile: "New profile",
  Add_Profile: "Add profile",
  Switch_Profile: "Switch / delete profile",
  Your_Text: "Your text...",
  Years: "Years",
  Weight: "Weight",
  Height: "Height",
  Dynamic: "Dynamic",
  Chat_Screen_ShareMessg: "Share a post",
  Player: "Player",
  Sociability: "Sociability",
  Lof: "Lof",
  Type_Of_Food: "Food",
  Type_Of_Home: "Habitat",
  Want_Childs: "Reproduction",
  Published: "Posts",
  Friends: "Friends",
  Yes: "Yes",
  No: "No",
  Send_Message: "Send message",
  Message: "Message",
  Allow_Geoloc: "Enable location",
  Allow_Notifs: "Enable notifications",
  Is_localisation_Datas: "Location data",
  Allow_Loveswap: "LoveSwap",
  Legals: "Legal",
  Informations: "Information",
  Your_Profile: "Your profile",
  Confidentiality: "Privacy",
  Security: "Security",
  Premium_Acces: "Premium account",
  Discussions: "Discussions",
  Adddiscussions: "Add discussion",
  Newdiscussions: "New discussion",
  Discussions_Post: "Share post",
  LoveSwap: "LoveSwap",
  AllowNotificationTxt: "Allow notifications and receive messages from other members.",
  PremiumIntroTxt:
    "The Premium subscription gives access to all app features. \n \n LoveSwap — to find breeding or adoption profiles by species, breed, or gender. \n \n Marketplace — to sell used items or accessories.",
  AllowGeolocalisationTxt:
    "Would you like to enable geolocation and appear on the map? Your pet’s position is automatically shifted within a 2 km radius to preserve your privacy. You can disable geolocation at any time.",
  AddAvatarpic: "Image gallery",
  MediasScreen: "Add media",
  Likes: "Likes",
  GetLocalisation: "Please wait... retrieving your coordinates...",
  Matches: "Matches",
  LoveLikers: "My likers",
  Likers: "Likers",
  Lovers: "Lovers",
  Swap_Settings: "Settings",
  Swap_Settings_txt: "Edit search fields:",
  Choose_Genre: "Select gender",
  Search_All_Genre: "Search all genders",
  Choose_Breed_: "Select breed...",
  Choose_Breed: "Select breed",
  Choose_Marker: "Search...",
  Search: "Search...",
  Search_All: "Name, species, breed, gender...",
  Add_Breed: "Add your breed to the list",
  Choose_Species: "Choose animal type for your search",
  UpdatePost: "Edit",
  Messages: "Messages",
  Share_Post: "New discussion",
  SharePost: "Share post",
  Sex_Signalment: "Sexual content",
  Hate_Signalment: "Hate speech or symbols",
  Violence_Signalment: "Violence or hate organization",
  Harrasment_Signalment: "Harassment or bullying",
  Illegal_Signalment: "Illegal content",
  Fake_Signalment: "False information",
  Why_Marker_Signalment: "Why are you reporting this marker?",
  Signalment_Details:
    "Select a reason for reporting. A message will be sent to moderation, and the content will be removed if it violates our guidelines.",
  MediasPolicy: "Add images for your pet’s profile",
  Signalment_AlreadySend: "You already submitted a report",
  Signalment_Send: "Your report has been sent",
  Why_Signalment: "Why are you reporting this post?",
  Add_Follower: "Follow",
  Re_Activate: "Reactivate this profile",
  No_Profils: "No profiles available",
  Remote_Follower: "Unfollow",
  Reproduction: "Reproduction",
  Author: "Author",
  Discuss_Creation: "Discussion created on",
},


  Modal: {
  Modify_Post: "Edit post",
  Delete_Post: "Delete",
  Delete_Confirmation: "Delete confirmation",
  Delete_Message: "Warning: deletion is permanent!",
  Warning: "Confirmation",
  confirmation: "Confirmation",
  birthdayTitle: "Warning",
  Delete: "Delete",
  Modify: "Edit",
  Cancel: "Cancel",
  Share: "Share",
  Select: "Select...",
  Ok: "OK",
  Empty_Fields: "Empty fields!",
  Signal: "Report",
  Block: "Block",
  understand: "I understand",
  WarningDeleteAccount: "Do you want to delete your account?",
  WarningDeleteAccountTxt: "You will permanently delete all associated profiles.",
  WarningBlokerTitle: "Do you want to block this profile?",
  WarningBlokerMessage:
    "Do you want to block this user?\n\nAssociated profiles will no longer appear in your feed or searches. You can unblock them anytime in your settings.",
  Warning_comment_message: "Do you want to delete this post?",
  warningDeleteMarker: "Do you want to delete this marker?",
  warningDeleteAlert: "Do you want to delete this alert?",
  warningDeleteLove: "Do you want to delete this liker?",
  warningDeleteLover: "Do you want to delete this lover?",
  warningDeleteProfile: "Do you want to delete this profile?",
  warningBirthday:
    "Unfortunately, you cannot register — your birth date is below the minimum age required for this application.",
  Warning_Delete_Account:
    "Do you want to permanently delete your account? Your profiles, images, posts, messages, comments, etc. will be permanently deleted.",
  Warning_Block_Member: "Do you want to block this member?",
  Warning_Block_Member2:
    "You will no longer see their profile or activities. They will no longer see yours.",
  Warning_Breed_Already_Exist: "This breed already exists!",
  Warning_Delete_Pic: "Do you want to delete this image?",
  Warning_Delete_Message: "Do you want to delete this message?",
  Warning_Delete_Lover: "Do you want to delete this match?",
  Warning_Delete_Liker: "Do you want to delete this liker?",
  Warning_Download: "Do you want to download this image?",
  Warning_DownloadVideo: "Do you want to download this video?",
  WelcomeModal: "Welcome",
  WelcomeGo: "Let's go...",
  WelcomeTextStars:
    "Individuals, associations, and professionals in the animal world — here you’ll find ways to communicate about your pets, share tips and good addresses with other owners.\n\nYou can, for breeding or adoption, search for the ideal partner nearby by species and breed. View other animals in your area, points of interest, or alerts for lost, stolen, or poisoned pets posted by others.\n\nDevelop a network of friends and mutual aid for our little companions.",
  WelcomeModalInfos:
    "You can create one or more profiles, exchange tips and advice with other owners, find breeders, professionals, or animal services, and meet other pets near you.",
  Welcome_Title: "Welcome to MyBuddyDiary",
  Welcome_Text:
    "You can create one or more profiles, exchange tips and advice with other owners, find breeders, professionals, or animal services, and meet other pets near you.",
  Welcome_AnimalMiss: "But first, you need to create a profile. Choose...",
  Valid: "OK",
  Create_Profil: "Create profile",
  Agreed: "Accept",
  Posts_Politics_Title: "Code of Conduct",
  Posts_Politics_Text:
    "According to MyBuddyDiary’s usage policy, we ask you to moderate your words when posting. Sexuality, vulgarity, proselytism, or any form of incitement are prohibited. Your images and texts must remain polite and respectful. You agree to follow the code of conduct stated above.",
  Posts_Politics_DeleteAccount:
    "If the instructions are not respected, the post will be deleted.",
  Marker_Details: "Description",
  Marker_Details_Typeof: "Define the marker type",
  Marker_Details_Title: "Title",
  Marker_Details_Description: "Description",
  Marker_Details_DescriptionLimite: "400 characters max",
  Marker_Details_Adress: "Address",
  Marker_Details_Save: "Save",
  Marker_Add: "Add marker",
  Alert: "Alert",
  Like_Post: "Like this post",
  Add_Comment: "Add a comment",
},


Form: {
  dog: "Dog",
  Username: "Username",
  Password: "Password",
  Password_Conf: "Password confirmation",
  Login: "Login",
  Create_Account: "Create account",
  Forgot_Password: "Forgot password",
  Activation_Code: "Do you have your activation code?",
  Already_Registered: "Already registered",
  Caption_Password: "* Must contain:",
  Symbols: "characters",
  Fname: "First name",
  Lname: "Last name",
  Email: "Email",
  Confirmation: "Confirmation",
  Confirm_Email: "Confirm email",
  Submit: "Submit",
  Geolocalisation: "Geolocation",
  PremiumPayLabel: "Activate Premium account",
  AllowGeolocalisation: "Allow geolocation",
  SetNewGeolocalisation: "Set new geolocation",
  AllowNotification: "Allow notifications",
  Allow_Loveswap: "Visible in LoveSwap",
  MatchInternationale: "Limit search distance",
  Adress: "Address",
  Street: "Street",
  StreetNumber: "Street number",
  Town: "City",
  Zip: "Postal code",
  Country: "Country",
  Private_Profile: "Private mode",
  New_Notifications: "Notifications",
  Current_Pwd: "Current password",
  New_Pwd: "New password",
  Add_Description: "Add a description...",
  Cancel: "Cancel",
  Delete: "Delete",
  Unblock: "Unblock",
  Type_Of: "Species",
  Breed: "Breed",
  Obligatory: "* Required",
  Genre: "Gender",
  Sterilisation: "Sterilized?",
  Date_Birth: "Date of birth",
  Lof: "L.O.F (Documents)",
  Small: "Small",
  Average: "Medium",
  Big: "Large",
  Yes: "Yes",
  No: "No",
  Alittle: "A little",
  Heavy: "Heavy",
  Light: "Light",
  Sex_Partner: "Reproduction",
  SearchAllSpecies: "Search all species",
  SearchAllBreeds: "Search all breeds",
  Adoption: "I am up for adoption",
  User_Adoption: "I’m looking to adopt a pet",
  Animal_Adoption: "I am available for adoption",
  User_identification: "Username, Name, Company",
  Download: "Download",
},



Error: {
  NoPost: "There are no posts.",
  No_Comments: "There are no comments.",
  No_Favorites: "There are no favorites...",
  No_Friends: "You have no buddies... Follow some pets to see their posts and chat with them.",
  No_Blokers: "There are no blocked members...",
  NoLikers: "There are no likes...",
  No_LoveLikers: "There are no likers...",
  No_Lovers: "There are no lovers...",
  No_Matches: "There are no matches...",
  No_ActionPost: "No posts available...",
  No_Notifications: "There are no notifications...",
  No_Discussions:
    "There are no discussions yet. Follow pets to chat with them. Add new discussions using the + button.",
  Bad_Fields: "Some fields are empty...",
  NoMessages: "There are no messages...",
  NoAlert: "There are no alerts...",
  Empty_Required_fields: "Required fields are empty...",
  No_Markers: "There are no markers...",
  No_Animal: "There are no profiles...",
  NoFollowers: "There are no followers...",
  No_Subscribers: "There are no buddies...",
  No_Bookmarks: "There are no bookmarks...",
  Email_Alreadyexist: "This email already exists...",
  Email_Notexist: "This email does not exist...",
  wrongdata: "Incorrect data...",
  Email_Novalid: "Invalid email...",
  Timme_Upgrade: "It's time to update...",
  Unvalid_App_Version:
    "Your app version is no longer compatible. An update is required for the app to function properly.",
},

Animal: {
  Dog: "Dog",
  Cat: "Cat",
  Rabbit: "Rabbit",
  Fish: "Fish",
  Bird: "Bird",
  Bug: "Insect",
  Horse: "Horse",
  Mouse: "Mouse",
  Reptile: "Reptile",
  Hamster: "Hamster",
  Ferret: "Ferret",
  Spider: "Spider",
  Femelle_Off: "Spayed female",
  Femelle_On: "Unspayed female",
  Male_Off: "Neutered male",
  Male_On: "Unneutered male",
  Lof: "Purebred",
  Wantbaby: "Available for breeding",
  Cow: "Cow",
  Goat: "Goat",
  Snake: "Snake",
  Pig: "Pig",
  Turtle: "Turtle",
  Heart: "Looking for adoption",
  Bull: "Bull",
  Sheep: "Sheep",
},

};