export default {
  myBuddy: "MyBuddy",
  welcome: "Bienvenido",
  form: {
    error: {
      baduser: "Usuario desconocido",
      bademail: "Correo electrónico no válido",
      badpwd: "Contraseña incorrecta",
      badpassword: "Contraseña no válida",
      badcode: "Código incorrecto",
      badfirstname: "Nombre no válido",
      badlastname: "Apellido no válido",
      badterms: "Términos no válidos",
      badattempt: "Intento incorrecto",
      isuseralready: "Este usuario ya existe",
      error: "Error",
      errorBackend: "Error del servidor",
    },
    success: "Éxito",
    done: "La información ha sido guardada",
  },

  auth: {
    errors: {
      baduser: "Usuario desconocido",
      bademail: "Correo electrónico no válido",
      badpwd: "Contraseña incorrecta",
      badpassword: "Contraseña no válida",
      badcode: "Código incorrecto",
      badfirstname: "Nombre no válido",
      badlastname: "Apellido no válido",
      badterms: "Términos no válidos",
      badattempt: "Intento incorrecto",
      isuseralready: "Este usuario ya existe",
      error: "Error",
    },
    logout: "Cerrar sesión",
    login: {
      login: "Iniciar sesión",
      submit: "Enviar",
      button: "Iniciar sesión",
      password: "Contraseña",
      title: "Iniciar sesión en MyBuddy",
      noAccount: "¿Aún no tienes cuenta?",
      forgot: {
        title: "¿Olvidaste tu contraseña?",
        button: "Recupérala aquí",
      },
    },
    signup: {
      timeToComplete: "Es hora de crear tu cuenta. Rellena todos los campos obligatorios.",
      firstName: "Nombre",
      lastName: "Apellido",
      email: "Correo electrónico",
      emailConf: "Confirmación de correo electrónico",
      button: "Registrarse",
      title: "Crear una cuenta",
      login: "¿Ya tienes una cuenta?",
      terms:
        "Al continuar con tu registro, aceptas nuestros términos y condiciones de uso",
      learn: "Más información",
    },
    forgot: {
      title: "Olvidé mi contraseña",
      resetpwd: "Restablecer contraseña",
      button: "Enviar",
      submit: "Enviar",
      errormail: "¡Correo electrónico no encontrado!",
      text: "Ingresa tu dirección de correo electrónico y recibe un código para establecer una nueva contraseña.",
    },
    verifyCode: {
      verifyCode: "Verifica el código que recibiste por correo electrónico",
      headerTxt: "Hemos enviado un correo electrónico",
      lineTxt:
        "Hemos enviado un código de verificación temporal a tu bandeja de entrada. Pégalo en el campo de abajo.",
      button: "Verificar código",
      title: "Verificación de código",
      inputText: "Código de verificación",
    },
    setPassword: {
      title: "Establecer contraseña",
      infos: "Últimos pasos para la creación de la cuenta. Guarda tu contraseña.",
      maxChar: "Al menos 8 caracteres",
      upperChar: "1 letra mayúscula",
      specialChar: "1 carácter especial",
      setPassword: "Establecer contraseña",
      button: "Completar registro",
      password: "Nueva contraseña",
      passwordConf: "Confirmar nueva contraseña",
      completeRegister: "Tu registro está completo",
      completeChangePwd: "Tu contraseña ha sido cambiada con éxito",
      validation: "Validación",
    },
  },

  dashboard: {
    title: "Tablero",
    welcome: "Bienvenido",
    feeds: "Este es tu tablero. Puedes obtener una visión general rápida de las últimas noticias de BE MY GUEST.",
    activeNotifications: "Activar notificaciones",
    newMessage: "Nuevo mensaje recibido",
    completeProfil: "Completa tu perfil",
  },

  mission: {
    title: "Misión",
  },

  message: {
    title: "Bandeja de entrada",
  },

  welcomePage: {
    welcomeText: "Puedes crear uno o más perfiles, intercambiar consejos y trucos con otros propietarios. Encuentra un criador, profesional o servicio para mascotas. Y conoce a otras mascotas cerca de ti.",
    WelcomeAnimalMiss: "Pero primero, necesitas crear un perfil, elige ...",
    chooseProfil: "Elige tu perfil",
    gotAnimal: "¿Tienes una o más mascotas?",
    noGotAnimal: "¿Estás buscando adoptar una mascota?",
    professionalAnimal: "¿Eres un profesional de mascotas?",
  },


  profile: {
    title: 'Perfil',
    welcome: "Bienvenido",
    logOut: "Cerrar sesión",
    chooseProfile: "Tus perfiles",
    adoption: "Adopción",
    animal: "Animal",
    society: "Sociedad",
  },

  wall: {
    title: 'Pantalla de Muro',
    unvalidAppVersion: "Su versión ya no es compatible. Es necesario actualizar para que la aplicación funcione correctamente.",
    newVersion: "Instalar la nueva versión",
  },
  userStatus: {
    chooseProfil: "Elige tu perfil",
    Got_Animal: "Eres dueño de uno o más animales",
    NoGot_Animal: "Estás buscando adoptar un animal",
    professionalAnimal: "Eres un profesional en el sector animal. Salud, Cría, Asociaciones, Refugios",
  },
  species: {
    title: "Especies",
    search: "Buscar ...",
    chooseSpecies: "Elige una especie",
  },
  breeds: {
    title: "Razas",
  },
  countries: {
    title: "Países",
  },

  animalProfile: {
    gender: "Género",
    years: "Años",
    buddies: "Amigos",
    followers: "Seguidores",
    privateProfile: "Perfil privado",
    informations: "Información",
    obligatory: "Obligatorio",
    title: "Perfil",
    name: "Nombre",
    man: "Hombre",
    woman: "Mujer",
    other: "Otro",
    firstName: "Nombre",
    fname: "Nombre / Nombre de usuario / Empresa",
    birthday: "Fecha de nacimiento",
    submit: "Enviar",
    height: "Altura",
    weight: "Peso",
    sociability: "Sociabilidad",
    sterilisation: "Esterilizado",
    noSterilisation: "",
    small: "Pequeño",
    average: "Mediano",
    tall: "Grande",
    lof: "Certificados y documentos",
    reproduction: "Cría",
    adoption: "Para adopción",
    description: "Descripción",
    searchDescription: "Especifica tu búsqueda",
    prosDescription: "¿Cuál es tu actividad?",
    dynamic: "Dinámico",
    player: "Juguetón",
    adoptionTitle: "Estás buscando adoptar",
    adoptionName: "¿Eres un particular, una asociación o un profesional?",
    yourSearch: "Estás buscando",
    private: "Cuenta invisible",
    dd: "DD",
    mm: "MM",
    aaaa: "AAAA",
    map: "¿Visible en el mapa?",
    love: "¿Visible en LoveSwap?",
    allowGeoloc: "Geolocalización:",
    email: "Correo electrónico",
    country: "País",
    town: "Ciudad",
    zipCode: "Código postal",
    adress: "Dirección",
  },

  addPicture: {
    title: "Añadir imagen",
  },

  fullScreenVideo: {
    title: "Vídeo a pantalla completa",
    confirm: "El medio se ha guardado en tu biblioteca.",
    close: "Cerrar",
  },

   videoScreen: {
    title: "Vidéo",
  },

  medias: {
    title: "Añadir medios",
    saveToLibrary: "Guardar en la biblioteca",
    videos: "Vídeos",
    camera: "Cámara",
    modify_profil: "Añadir una imagen desde ...",
    library: "Galería",
    download: "Descargar desde:",
    takePicture: "Tomar una foto",
    takeVideo: "Grabar un vídeo",
    postVideo: "Publicar el vídeo",
    got_Animal: "Eres dueño de una o más mascotas ...",
    noGot_Animal:
      "Estás buscando adoptar o eres un profesional de mascotas. Salud, Cría, Asociaciones, Refugios ...",
    share_Video: "Compartir este vídeo",
    videoProcessing:
      "Dependiendo de la calidad de tu conexión y del tipo de vídeo, el procesamiento puede tardar un poco.",
    pleaseWait: "El vídeo se está procesando ... Por favor, espera",
  },

  profiles: {
    title: "Tus perfiles",
    male: "Hombre",
    female: "Mujer",
    other: "Otro",
    localisation: "Ubicación",
     adress: "Dirección",
  },

  addPost: {
    title: "Nueva publicación",
    editPost: "Editar publicación",
    addLegend: "Añadir una descripción ...",
    publish: "Compartir",
    mediaTraitment: "Procesando medios",
  },

  legends: {
    title: "Leyendas",
  },

  signalment: {
    title: "Reporte",
  },
  addComment: {
    title: "Comentarios",
    answer: "Responder...",
    addFollower: "Seguir",
    removeFollower: "Dejar de seguir",
    liked: "Me gusta",
    delete: "Borrar",
    commentary: "Comentario(s)",
    addComments: "Añadir",
    modify: "Editar",
    publish: "Publicar",
    response: "En respuesta a ",
    tendancyResponse: "Respuestas de tendencia",
  },

  loveSwap: {
  noMoreCards: "No hay más cartas",
  like: "Me gusta",
  noLike: "No me gusta",
  yes: "Sí",
  no: "No",
  loveMatch: "LoveMatch",
  likers: "Likers",
  searchSwapDistance: "Elige la distancia de búsqueda",
  all: "Todos los géneros",
  allSpeciesSearch: "Todas las especies",
  allBreedsSearch: "Todas las razas",
  specifySearch: "Especifica tu búsqueda:",
  loveNewSearch: "Nueva búsqueda",
  reproduction: "Reproducción",
  adoption: "Adopción",
  undo: "Volver",
  chooseSpecies: "Elegir especie",
  chooseBreeds: "Elegir raza",
  search: "Buscar"
},


  premium: {
    title: "Cuenta Premium",
    activate: "Activar tu Cuenta Premium",
  },

  alert:{
  title: "Alerta, solicitud de ayuda",
  alertSubject: "Voulez vous activer l'alerte et voir sur le wall un menu deroulnt correspondnat a votre alerte dans les 20km ",
},
launchAlert:{
  title: "Información",
  alertSubject: "¿Desea activar la alerta y ver en el muro un menú desplegable correspondiente a su alerta en un radio de 20 km?",
  alertPinPlace : "Marque en el mapa el lugar donde su animal desapareció, fue robado, o las zonas de riesgo.\n",
  alertPinPCancel : "Cancelar con ",
  savePinAlert : "Guárdelo con ",
  contact: "Contactar al propietario",
  informations: "Va a definir a partir de un punto central una zona de alerta para todos los usuarios de MyBuddy.",
},
alertDetails: {
  title: "Detalles de la alerta",
  lost: "Perdido",
  stolen: "Robado",
  hurted: "Herido",
  poisonned: "Envenenado",
  subject: "Está a punto de lanzar una alerta general para todos los usuarios de MyBuddy en un radio de 50 km.\n\nComplete los siguientes campos",
  alertType: "Defina su alerta para",
  textTooLong: "Ha superado el límite de texto.",
  warning: "Atención",
  addImage: "Añadir fotos recientes"
},
alertList: {
  title: "Sus alertas",
},

  loveMatch: {
    title: "Tus Matches",
    matches: "Matches",
    myLikers: "Les gustas",
    myLovers: "Tus Matches",
  },

  loveLikers: {
    title: "Les gustas",
  },

  animalDetails: {
    title: "Detalles del Animal",
    posts: "Publicaciones",
    followers: "Seguidores",
  },

  postList: {
    title: "Lista de publicaciones",
  },

  likerList: {
    title: "Lista de personas a las que le gustas",
  },

  friendList: {
    title: "Lista de amigos",
  },

  followerList: {
    title: "Lista de seguidores",
  },

  favoriteList: {
    title: "Lista de favoritos",
  },

  bookmarksList: {
    title: "Lista de marcadores",
  },

  modalSettings: {
    switchProfile: "Cambiar / Eliminar",
    profile: "Perfil",
    addProfile: "Añadir un perfil",
    buddies: "Amigos",
    likes: "Me gusta",
    blockedMembers: "Miembros bloqueados",
    settings: "Ajustes",
    legals: "Información legal",
    logOut: "Cerrar sesión",
    geolocalisation: "Geolocalización",
    activeGeolocalisation: "Activar geolocalización",
    notifications: "Notificaciones",
    favorite: "Publicaciones favoritas",
    userSettings: "Ajustes de usuario",
    alert: "Alerta de animal perdido o robado"
  },

  sharePost: {
    title: "Compartir publicación",
  },

  sendPost: {
    title: "Compartir una publicación",
  },

  chatMessage: {
    title: "Mensaje de chat",
  },

  chatRoom: {
    title: "Añadir mensaje",
  },

  notifications: {
    title: "Notificaciones",
    AllowNotificationTxt: "Permitir notificaciones y recibir mensajes de otros miembros.",
    activeNotifications: "Activar notificaciones",
  },

  logOut: {
    title: "Cerrar sesión",
    seeYouSoon: "Hasta pronto...",
  },

  legal: {
    title: "Acuerdo legal",
  },

  Medias: {
    SaveToLibrary: "Guardar en la biblioteca",
    Videos: "Vídeos",
    Camera: "Cámara",
    Modify_profil: "Añadir una imagen desde ...",
    Library: "Galería de medios",
    Download: "Descargar desde:",
    takepicture: "Tomar una foto",
    Takevideo: "Grabar un nuevo vídeo",
    PostVideo: "Publicar el vídeo",
    sendVideo: "Usar el vídeo",
    Got_Animal: "Eres dueño de una o más mascotas ...",
    NoGot_Animal:
      "Estás buscando adoptar o eres un profesional de mascotas. Salud, Cría, Asociaciones, Refugios ...",
    Share_Video: "Compartir este vídeo",
    VideoProcessing:
      "Dependiendo de la calidad de tu conexión y del tipo de vídeo, el procesamiento puede tardar un poco.",
    PleaseWait: "El vídeo se está procesando ... Por favor, espera",
  },

  messages: {
    deletedRoom: "Esta conversación ha sido eliminada",
  },

  user: {
    searchAdopt: "Buscando adoptar:",
    noPosts: "No hay publicaciones",
    published: "Publicaciones",
  },

  marker: {
    selectMarker: "Elige un tipo de marcador",
    update: "Actualizar",
    title: "Lista de marcadores",
    details: "Detalles del marcador",
  },

  bloker: {
    title: "Perfiles bloqueados",
    unblock: "Desbloquear",
  },
  userSetting: {
    title: "Ajustes de usuario",
    changeEmail: "Cambiar correo electrónico",
    changePwd: "Cambiar contraseña",
    deleteAccount: "Eliminar cuenta",
    isPremium: "Cuenta Premium",
    changeEmailTxt: "Para cambiar tu correo electrónico, por favor, introduce tu correo electrónico actual. Recibirás un código para actualizar tu dirección.",
    newAdress: "Nueva dirección de correo electrónico",
    confirmEmail: "Confirmar nuevo correo electrónico",
    accountInformations: "Información de la cuenta",
    gender: "Tu género",
    country: "¿Tu país?",
    search: "Buscar",
    userUpdated: "Tus ajustes han sido actualizados con éxito.",
    actualEmail: "Correo electrónico actual",
    newEmail: "Nuevo correo electrónico",
    confirmNewEmail: "Confirmar nuevo correo electrónico",
    alreadyExist: "Esta dirección ya existe",
    error: "Error",
    newPwd: "Nueva contraseña",
    newPwdConfirm: "Confirmar nueva contraseña",
  },

  alert: {
  addPicture: "Agregar fotos",
  title: "Alerta, solicitud de ayuda",
  alertSubject: "¿Desea activar la alerta y ver en el muro un menú desplegable correspondiente a su alerta en un radio de 20 km?",
},

launchAlert: {
  title: "Información",
  alertSubject: "¿Desea activar la alerta y ver en el muro un menú desplegable correspondiente a su alerta en un radio de 20 km?",
  alertPinPlace: "Marque en el mapa el lugar donde su mascota se perdió, fue robada o las zonas de riesgo.\n",
  alertPinPCancel: "Cancelar con ",
  savePinAlert: "Guardar con ",
  contact: "Contactar al propietario",
  informations: "Definirá desde un punto central una zona de alerta para todos los usuarios de BuddyDiary.",
},

alertDetails: {
  title: "Detalles de la alerta",
  lost: "Perdido",
  stolen: "Robado",
  hurted: "Herido",
  poisonned: "Envenenado",
  subject: "Está a punto de lanzar una alerta general para todos los usuarios de MyBuddy en un radio de 50 km.\n\nComplete los siguientes campos",
  alertType: "Definir su alerta para",
  textTooLong: "Ha excedido el límite de texto.",
  warning: "Atención",
  addImage: "Agregar fotos recientes",
  maxAlert: "Ha superado el número de alertas disponibles. Cambie al modo Premium para agregar más alertas.",
},

alertList: {
  title: "Sus alertas",
},
  Page: {
  Male: "Masculino",
  Female: "Femenino",
  Adoption: "Adopción",
  Active_Premium: "Debe activar su cuenta Premium para usar LoveSwap.",
  Nomore_Cards: "No hay perfiles que coincidan con su búsqueda.\n\n¿Ver los likers?",
  Health_Place: "Salud de mi mascota",
  Alert_Lost: "Alerta, he perdido a mi mascota",
  Market_Place: "Mercado",
  My_Blokers: "Miembros bloqueados",
  My_Likes: "Mis likes",
  Download: "Descargar",
  Downloading: "Cargando...",
  Markerpin_1: "Coloque su marcador en el mapa. Cancelar con ",
  Markerpin_2: "Guárdelo con ",
  Other_Animals: "Otros animales",
  All_Animals: "Todos los animales",
  Answer: "Responder",
  Animal_Create_Profile: "Nuevo perfil",
  Visitor_Create_Profile: "Perfil",
  Mentions_Legals: "Aviso legal",
  Member_Date: "Miembro desde",
  Premium_Member_Date: "Miembro Premium desde",
  Block_Member: "Bloquear",
  Member_No: "Este perfil ha sido eliminado",
  Subscriptions: "Buddies",
  Blokers: "Miembros bloqueados",
  My_Subscriptions: "Mis buddies",
  Subscribers: "Buddies",
  Abonned: "Suscriptores",
  NoLoveLikerList: "Perfiles no seleccionados",
  Marker_Detail: "Marcador",
  Marker_List: "Lista de marcadores",
  Add_Friends: "Agregar como buddy",
  Delete_Friend: "Eliminar",
  Day: "Día",
  Month: "Mes",
  Year: "Año",
  General_settings: "Ajustes",
  Legends: "Leyendas",
  Loading: "Cargando...",
  Posts: "Publicaciones",
  Followers: "Seguidores",
  Follow: "Seguir",
  Store: "Tiendas",
  Health: "Salud",
  Services: "Servicios",
  Outdoor: "Exterior",
  Comments: "Comentarios",
  Add_Comments: "Agregar comentario",
  Answer_Comments: "Responder...",
  Commentary: "Comentario(s)",
  Add_Commentary: "Comentarios",
  Add_Message: "Enviar mensaje",
  Add_Typeof: "Agregar especie",
  Add_Breed_Txt: "Puede agregar una raza adicional si no está en la lista...",
  Publish: "Publicar",
  Modify: "Editar",
  Member_Since: "Miembro desde",
  Liked: "Me gusta",
  Liked_by: "Gustado por",
  Animal_Details: "Identidad",
  Animals_Map: "Mapa",
  Swap_Fiancy: "Love swap",
  Alert_Lost: "Alerta: he perdido a mi mascota",
  Seefriends: "Seguidores",
  SeePostfriends: "Amigos",
  SeeLegends: "Iconos de leyenda",
  Signalment: "Informe",
  Marker_Signalment: "Informe de marcador",
  My_Friends: "Mis buddies",
  Post_Likers: "Likers",
  Settings: "Ajustes",
  AnimalsMap: "Mapa de animales",
  Next: "Siguiente",
  Validate: "Validar",
  Add: "Agregar",
  Animal_Profile: "Editar perfil",
  BreedScreen: "Raza",
  Add_Animal: "Agregar animal",
  Create_New_Animal: "Agregar un animal",
  List_Animal: "Perfiles",
  Create_Profil: "Crear perfil",
  Add_BreedScreen: "Agregar nueva raza",
  Add_BreedScreenTxt: "Agregue la raza de su mascota...",
  SpeciesScreen: "Especie",
  Choose_Town: "Su ciudad",
  Privatie: "Privado",
  Age: "años",
  No_Profil: "Complete el perfil...",
  Account: "Cuenta",
  Delete_Account: "Eliminar mi cuenta",
  Delete_Account_Txt: "Todos sus mensajes e información serán eliminados permanentemente...",
  Accept_Legals: "Reconoce haber leído y aceptado nuestra política de privacidad",
  Delete: "Eliminar",
  Just_Now: "Justo ahora...",
  Your_Account: "Su cuenta",
  Choose_Profil: "Elegir perfil",
  Choose_Typeof: "Elegir especie",
  Change_Profil: "Cambiar perfil",
  See_Profile: "Ver perfil",
  User_Profile: "Su perfil",
  Password: "Contraseña",
  Soon_Available: "Próximamente...",
  LoveMessage: "Mensajes",
  Publicity: "Publicidad",
  Notifications: "Notificaciones",
  Premium_Status: "Cuenta Premium",
  Geolocalisation: "Geolocalización",
  Log_Out: "Cerrar sesión",
  SeeYouSoon: "Hasta pronto...",
  Send: "Enviar",
  Placeholder_Youressage: "Su mensaje...",
  Chat_Screen: "Pantalla de chat",
  Profile: "Perfil",
  New_Profile: "Nuevo perfil",
  Add_Profile: "Agregar perfil",
  Switch_Profile: "Cambiar / eliminar perfil",
  Your_Text: "Su texto...",
  Years: "Años",
  Weight: "Peso",
  Height: "Tamaño",
  Dynamic: "Dinámico",
  Chat_Screen_ShareMessg: "Compartir una publicación",
  Player: "Jugador",
  Sociability: "Sociabilidad",
  Lof: "Lof",
  Type_Of_Food: "Alimento",
  Type_Of_Home: "Hábitat",
  Want_Childs: "Reproducción",
  Published: "Publicaciones",
  Friends: "Amigos",
  Yes: "Sí",
  No: "No",
  Send_Message: "Enviar mensaje",
  Message: "Mensaje",
  Add_Friends: "Agregar amigos",
  Allow_Geoloc: "Activar geolocalización",
  Allow_Notifs: "Activar notificaciones",
  Is_localisation_Datas: "Datos de ubicación",
  Allow_Loveswap: "LoveSwap",
  Legals: "Legales",
  Informations: "Información",
  Your_Profile: "Su perfil",
  Confidentiality: "Confidencialidad",
  Security: "Seguridad",
  Premium_Acces: "Cuenta Premium",
  Discussions: "Discusiones",
  Adddiscussions: "Agregar discusiones",
  Newdiscussions: "Nueva discusión",
  Discussions_Post: "Compartir publicación",
  LoveSwap: "LoveSwap",
  AllowNotificationTxt: "Permitir notificaciones y recibir mensajes de otros miembros.",
  PremiumIntroTxt: "La suscripción Premium permite acceder a todas las funcionalidades de la aplicación.\n\nLoveSwap, para buscar perfiles de reproducción o adopción por especie, raza o género.\n\nMarket Place, para vender objetos o accesorios usados.",
  AllowGeolocalisationTxt: "¿Desea beneficiarse de la geolocalización y aparecer en el mapa? La posición de su mascota se modifica voluntariamente en un radio de 2 km para preservar su anonimato. Puede desactivar la geolocalización en cualquier momento.",
  AddAvatarpic: "Galería de imágenes",
  MediasScreen: "Agregar medios",
  Likes: "Likes",
  GetLocalisation: "Espere... Recuperando sus coordenadas...",
  Matches: "Matches",
  LoveLikers: "Mis Likers",
  Likers: "Likers",
  Lovers: "Lovers",
  Swap_Settings: "Ajustes",
  Swap_Settings_txt: "Modifique los campos de búsqueda:",
  Choose_Genre: "Seleccione el género",
  Search_All_Genre: "Buscar todos los géneros",
  Choose_Breed_: "Seleccione la raza...",
  Choose_Breed: "Seleccione la raza",
  Choose_Marker: "Buscar...",
  Search: "Buscar...",
  Search_All: "Nombre, Especie, Raza, Género...",
  Add_Breed: "Agregar su raza a la lista",
  Choose_Species: "Elija el tipo de animal en su búsqueda",
  UpdatePost: "Editar",
  Messages: "Mensajes",
  Share_Post: "Nueva discusión",
  SharePost: "Compartir publicación",
  Sex_Signalment: "Contenido sexual",
  Hate_Signalment: "Discurso u símbolo de odio",
  Violence_Signalment: "Violencia u organización de odio",
  Harrasment_Signalment: "Intimidación y acoso",
  Illegal_Signalment: "Contenido ilegal",
  Fake_Signalment: "Información falsa",
  Why_Marker_Signalment: "¿Por qué informa este marcador?",
  Signalment_Details: "Seleccione el motivo del informe. Se enviará un mensaje a la moderación y se eliminará si el contenido no cumple con nuestra política ética.",
  MediasPolicy: "Agregue imágenes para el perfil de su mascota",
  Signalment_AlreadySend: "Ya ha enviado un informe",
  Signalment_Send: "Su informe ha sido enviado",
  Why_Signalment: "¿Por qué informa esta publicación?",
  Add_Follower: "Seguir",
  Re_Activate: "Reactivar este perfil",
  No_Profils: "No hay perfiles",
  Remote_Follower: "Dejar de seguir",
  Reproduction: "Reproducción",
  Author: "Autor",
  Discuss_Creation: "Discusión creada el",
},



  Modal: {
  Modify_Post: "Editar publicación",
  Delete_Post: "Eliminar",
  Delete_Confirmation: "Confirmación de eliminación",
  Delete_Message: "Atención: ¡Eliminar es permanente!",
  Warning: "Confirmación",
  confirmation: "Confirmación",
  birthdayTitle: "Atención",
  Delete: "Eliminar",
  Modify: "Editar",
  Cancel: "Cancelar",
  Share: "Compartir",
  Select: "Seleccione...",
  Ok: "OK",
  Empty_Fields: "¡Campos vacíos!",
  Signal: "Reportar",
  Block: "Bloquear",
  understand: "Entendido",
  WarningDeleteAccount: "¿Desea eliminar su cuenta?",
  WarningDeleteAccountTxt: "Eliminará permanentemente todos los perfiles asociados.",
  WarningBlokerTitle: "¿Desea bloquear este perfil?",
  WarningBlokerMessage: "¿Desea bloquear a este usuario?\n\nLos perfiles asociados ya no aparecerán en su feed ni en sus búsquedas. Puede desbloquearlo en cualquier momento desde sus ajustes.",
  Warning_comment_message: "¿Desea eliminar esta publicación?",
  warningDeleteMarker: "¿Desea eliminar este marcador?",
  warningDeleteAlert: "¿Desea eliminar esta alerta?",
  warningDeleteLove: "¿Desea eliminar este liker?",
  warningDeleteLover: "¿Desea eliminar este lover?",
  warningDeleteProfile: "¿Desea eliminar este perfil?",
  warningBirthday: "Desafortunadamente no puede registrarse, su fecha de nacimiento es inferior a la edad mínima requerida para esta aplicación.",
  Warning_Delete_Account: "¿Desea eliminar definitivamente su cuenta? Sus perfiles, imágenes, publicaciones, mensajes, comentarios, etc. serán eliminados permanentemente.",
  Warning_Block_Member: "¿Desea bloquear a este miembro?",
  Warning_Block_Member2: "Ya no verá su perfil ni sus actividades. El miembro tampoco verá su perfil ni sus actividades.",
  Warning_Breed_Already_Exist: "¡Esta raza ya existe!",
  Warning_Delete_Pic: "¿Desea eliminar esta imagen?",
  Warning_Delete_Message: "¿Desea eliminar este mensaje?",
  Warning_Delete_Lover: "¿Desea eliminar este match?",
  Warning_Delete_Liker: "¿Desea eliminar este liker?",
  Warning_Download: "¿Desea descargar esta imagen?",
  Warning_DownloadVideo: "¿Desea descargar este video?",
  WelcomeModal: "Bienvenido",
  WelcomeGo: "Vamos allá...",
  WelcomeTextStars: "Particulares, asociaciones y profesionales del mundo animal encontrarán aquí medios para comunicarse sobre su(s) mascota(s), intercambiar consejos o buenas direcciones con otros propietarios.\n\nDentro de un contexto de cría o reproducción, podrá buscar la pareja ideal cerca de usted, por especie y raza. Visualizar otros animales cercanos, puntos de interés geográfico o alertas de pérdida, robo o envenenamiento publicadas por otros propietarios.\n\nDesarrollar una red de amigos y apoyo para nuestros pequeños compañeros.",
  WelcomeModalInfos: "Puede crear uno o varios perfiles, intercambiar con otros propietarios consejos, trucos y buenas prácticas. Encontrar un criador, un profesional o un servicio animal. Y conocer otros animales cerca de usted.",
  Welcome_Title: "Bienvenido a MyBuddyDiary",
  Welcome_Text: "Puede crear uno o varios perfiles, intercambiar con otros propietarios consejos, trucos y buenas prácticas. Encontrar un criador, un profesional o un servicio animal. Y conocer otros animales cerca de usted.",
  Welcome_AnimalMiss: "Pero primero, debe crear un perfil, elija...",
  Valid: "OK",
  Create_Profil: "Crear perfil",
  Agreed: "Aceptar",
  Posts_Politics_Title: "Reglas de conducta",
  Posts_Politics_Text: "De acuerdo con la política de uso de MyBuddyDiary, le pedimos moderar sus comentarios en las publicaciones. Sexualidad, vulgaridad, proselitismo o incitaciones de cualquier forma están prohibidas. Sus imágenes y textos deben ser corteses y respetuosos. Se compromete a seguir la política de conducta mencionada arriba.",
  Posts_Politics_DeleteAccount: "Si no cumple las instrucciones, la publicación será eliminada.",
  Marker_Details: "Descripción",
  Marker_Details_Typeof: "Defina el tipo de marcador",
  Marker_Details_Title: "Título",
  Marker_Details_Description: "Descripción",
  Marker_Details_DescriptionLimite: "Máx. 400 caracteres",
  Marker_Details_Adress: "Dirección",
  Marker_Details_Save: "Guardar",
  Marker_Add: "Agregar marcador",
  Alert: "Alerta",
  Like_Post: "Dar like a esta publicación",
  Add_Comment: "Agregar un comentario",
},

  Form: {
    dog: "Perro",
    Username: "Nombre de usuario",
    Password: "Contraseña",
    Password_Conf: "Confirmación de contraseña",
    Login: "Iniciar sesión",
    Create_Account: "Crear cuenta",
    Forgot_Password: "Contraseña olvidada",
    Activation_Code: "¿Tienes tu código de activación?",
    Already_Registered: "Ya registrado",
    Caption_Password: "* Debe contener:",
    Symbols: "caracteres",
    Fname: "Nombre",
    Lname: "Apellido",
    Email: "Correo electrónico",
    Confirmation: "Confirmación",
    Confirm_Email: "Confirmar correo electrónico",
    Submit: "Enviar",
    Geolocalisation: "Geolocalización",
    PremiumPayLabel: "Activar cuenta Premium",
    AllowGeolocalisation: "Permitir geolocalización",
    SetNewGeolocalisation: "Establecer nueva geolocalización",
    AllowNotification: "Permitir notificaciones",
    Allow_Loveswap: "Visible en LoveSwap",
    MatchInternationale: "Limitar distancia de búsqueda",
    Adress: "Dirección",
    Street: "Calle",
    StreetNumber: "Número de calle",
    Town: "Ciudad",
    Zip: "Código postal",
    Country: "País",
    Private_Profile: "Modo privado",
    New_Notifications: "Notificaciones",
    Current_Pwd: "Contraseña actual",
    New_Pwd: "Nueva contraseña",
    Add_Description: "Agregar una descripción...",
    Cancel: "Cancelar",
    Delete: "Eliminar",
    Unblock: "Desbloquear",
    Type_Of: "Especie",
    Breed: "Raza",
    Obligatory: "* Requerido",
    Genre: "Género",
    Sterilisation: "¿Esterilizado?",
    Date_Birth: "Fecha de nacimiento",
    Lof: "L.O.F (Documentos)",
    Small: "Pequeño",
    Average: "Mediano",
    Big: "Grande",
    Yes: "Sí",
    No: "No",
    Alittle: "Un poco",
    Heavy: "Pesado",
    Light: "Ligero",
    Sex_Partner: "Cría",
    SearchAllSpecies: "Buscar todas las especies",
    SearchAllBreeds: "Buscar todas las razas",
    Adoption: "Estoy disponible para adopción",
    User_Adoption: "Estoy buscando adoptar una mascota",
    Animal_Adoption: "Estoy disponible para adopción",
    User_identification: "Nombre de usuario, Nombre, Empresa",
    Download: "Descargar"
  },



  EError: {
  NoPost: "No hay publicaciones",
  No_Comments: "No hay comentarios",
  No_Favorites: "No hay favoritos...",
  No_Friends: "No hay buddies... Suscríbase a animales para ver sus publicaciones y chatear con ellos.",
  No_Blokers: "No hay miembros bloqueados...",
  NoLikers: "No hay likes...",
  No_LoveLikers: "No hay likers...",
  No_Lovers: "No hay lovers...",
  No_Matches: "No hay matches...",
  No_ActionPost: "No hay publicaciones...",
  No_Notifications: "No hay notificaciones...",
  No_Discussions: "Aún no hay discusiones. Siga a los animales para conversar con ellos. Agregue otras discusiones con el +",
  Bad_Fields: "Algunos campos están vacíos...",
  NoMessages: "No hay mensajes...",
  NoAlert: "No hay alertas...",
  Empty_Required_fields: "Los campos requeridos están vacíos...",
  No_Markers: "No hay marcadores...",
  No_Animal: "No hay perfiles...",
  NoFollowers: "No hay seguidores...",
  No_Subscribers: "No hay buddies...",
  No_Bookmarks: "No hay marcadores guardados...",
  Email_Alreadyexist: "El correo electrónico ya existe...",
  Email_Notexist: "El correo electrónico no existe...",
  wrongdata: "Los datos son incorrectos...",
  Email_Novalid: "Correo electrónico no válido...",
  Timme_Upgrade: "Es hora de actualizar...",
  Unvalid_App_Version: "Su versión ya no es compatible. Es necesario actualizar la aplicación para que funcione correctamente."
},

  Animal: {
    Dog: "Perro",
    Cat: "Gato",
    Rabbit: "Conejo",
    Fish: "Pez",
    Bird: "Pájaro",
    Bug: "Insecto",
    Horse: "Caballo",
    Mouse: "Ratón",
    Reptile: "Reptil",
    Hamster: "Hámster",
    Ferret: "Hurón",
    Spider: "Araña",
    Femelle_Off: "Hembra esterilizada",
    Femelle_On: "Hembra no esterilizada",
    Male_Off: "Macho castrado",
    Male_On: "Macho no castrado",
    Lof: "De raza pura",
    Wantbaby: "Disponible para cría",
    Cow: "Vaca",
    Goat: "Cabra",
    Snake: "Serpiente",
    Pig: "Cerdo",
    Turtle: "Tortuga",
    Heart: "Buscando adopción",
    Bull: "Toro",
    Sheep: "Oveja"
  }
};