export default {

  myBuddy: "MyBuddy",
  welcome: 'Bienvenue',
  form: {
    error: {
      baduser: "Utilisateur inconnu",
      bademail: "Email incorrect",
      badpwd: "Mot de passe incorrect",
      badpassword: "Mot de passe non valide",
      badcode: "Code incorrect",
      badfirstname: "Prénom incorrect",
      badlastname: "Nom incorrect",
      badterms: "Conditions incorrectes",
      badattempt: "Mauvaise tentative",
      isuseralready: "Cet utilisateur existe déjà",
      error: "Erreur",
      errorBackend: "Erreur du serveur",
    },
    success: "Succès",
    done: "Les informations ont été enregistrées",
  },
  auth: {
    errors: {
      baduser: "Utilisateur inconnu",
      bademail: "Email incorrect",
      badpwd: "Mot de passe incorrect",
      badpassword: "Mot de passe non valide",
      badcode: "Code incorrect",
      badfirstname: "Prénom incorrect",
      badlastname: "Nom incorrect",
      badterms: "Conditions incorrectes",
      badattempt: "Mauvaise tentative",
      isuseralready: "Cet utilisateur existe déjà",
      error: "Erreur",
    },
    logout: "Se déconnecter",
    login: {
      login: "Connexion",
      submit: "Valider",
      button: "Se connecter",
      password: "Mot de passe",
      title: "Connexion à BuddyDiary",
      noAccount: "Pas encore de compte ?",
      forgot: {
        title: "Mot de passe oublié ?",
        button: "Récupérez-le ici",
      },
    },
    signup: {
      timeToComplete: "C'est le moment de créer votre compte. Remplissez tous les champs demandés.",
      firstName: "Prénom",
      lastName: "Nom",
      email: "Email",
      emailConf: "Confirmation de l'email",
      button: "S'inscrire",
      title: "Créer un compte",
      login: "Vous avez déjà un compte ?",
      terms:
        "En poursuivant votre inscription, vous acceptez \n nos conditions générales d'utilisation",
      learn: "En savoir plus",
    },
    forgot: {
      title: "Mot de passe oublié",
      resetpwd: "Réinitialiser le mot de passe",
      button: "Envoyer",
      submit: "Valider",
      errormail: "Email introuvable !",
      text: "Saisissez votre adresse email et recevez un code pour définir un nouveau mot de passe.",
    },
    verifyCode: {
      verifyCode: "Vérifiez le code reçu par email",
      headerTxt: "Nous avons envoyé un email",
      lineTxt:
        "Nous avons envoyé un code de vérification temporaire à votre boîte mail. Collez-le dans le champ ci-dessous.",
      button: "Vérifier le code",
      title: "Vérification du code",
      inputText: "Code de vérification",
    },
    setPassword: {
      title: "Définir un mot de passe",
      infos:  "Dernières étapes pour la création du compte. Sauvegardez votre mot de passe.",
      maxChar: "Au moins 8 caractères",
      upperChar: "1 lettre majuscule",
      specialChar: "1 caractère spécial",
      setPassword: "Définir le mot de passe",
      button: "Terminer l'inscription",
      password: "Nouveau mot de passe",
      passwordConf: "Confirmer le nouveau mot de passe",
      completeRegister: "Votre inscription est terminée",
      completeChangePwd: "Votre mot de passe a été modifié avec succès",
      validation: "Succès",
    },
  },
 dashboard: {
  title: "Tableau de bord",
  welcome: "Bienvenue",
  feeds: "Voici votre tableau de bord. Vous pouvez avoir un aperçu rapide des derniers flux BE MY GUEST.",
  activeNotifications: "Activer les notifications",
  newMessage: "Nouveau message reçu",
  completeProfil: "Complétez votre profil",
},
permission: {
  title: "Demande d'autorisation pour utiliser la camera",
  accept: "Accepter",
},
mission: {
  title: "Mission",
},
message: {
  title: "Boîte de réception",
},

  welcome: {
    welcomeText: "Vous pouvez créer un ou plusieurs profils, échanger avec d’autres propriétaires les bons plans, les conseils, les trucs et astuces. Trouver un éleveur, un professionel ou encore un service animalier. Et rencontrer d’autres animaux près de chez vous.",
    WelcomeAnimalMiss : " Mais tout d'abord, vous devez créer un profil, choisissez ...",
    chooseProfil: "Choisissez votre profil", 
    gotAnimal: "Vous êtes proprietaire d'un ou plusieurs animaux ?",
    noGotAnimal: "Vous cherchez à adopter un animal ?",
    professionalAnimal: "Vous êtes un professionnel du secteur animalier ?",
  },

  profile : {
    title : 'Profile',
    welcome: "Welcome",
    logOut: "Log out",
    chooseProfile: "Vos profils",
    adoption: "Adoption",
    animal: "Animal",
    society: "Société",
  },

  wall: {
    title: 'WallScreen',
    unvalidAppVersion: "Votre version n'est plus compatible. La mise à jour est necessaire pour que l'application puisse fonctionner correctement.",
    newVersion: "Installler la nouvelle version",
  },

  userStatus: {
    chooseProfil: "Choisissez votre profil", 
    Got_Animal: "Vous êtes proprietaire d'un ou plusieurs animaux",
    NoGot_Animal: "Vous cherchez à adopter un animal",
    professionalAnimal: "Vous êtes un professionnel du secteur animalier. Santé, Elevage, Associations, Refuges",
  },
  species: {
    title: "Especes",
    search: "Recherche ...",
    chooseSpecies: "Choisir une espece",
  },
  breeds: {
    title: "Races",
  },
  countries: {
    title: "Pays",
  },
  animalProfile: {
    gender: "Genre",
    years: "ans",
    buddies: 'Buddies',
    followers: "Abonnes",
    privateProfile : "Profil privé",
    informations: "Informations",
    obligatory: 'Obligatoire',
    title: "Profile",
    name: "Nom",
    man: "Homme",
    woman:"Femme",
    other: "autre",
    firstName:"Prénom",
    fname: "Prénom / Pseudo / Raison Social",
    birthday: 'Date de naissance',
    submit: "Valider",
    height: "Taille",
    weight: "Poids",
    sociability: "Sociabilité",
    sterilisation: "Stérilisé(e)",
    noSterilisation: "",
    small: "Petit",
    average: "Moyen",
    tall: "Grand",
    lof: "Certificats et documents",
    reproduction: "Reproduction",
    adoption: "A adopter",
    description: "Description",
    searchDescription: "Précisez votre recherche",
    prosDescription: "Quelle est votre activité ?",
    dynamic: "Dynamique",
    player: "Joueur",
    adoptionTitle: "Vous cherchez a adopter ",
    adoptionName: 'Vous êtes un particulier, une association, un professionnel ?',
    yourSearch: "Vous recherchez",
    private: "Compte invisible",
    dd: "DD",
    mm: "MM",
    aaaa: "AAAA",
    map: "Visible sur la carte ?",
    love: "Visible sur le loveSwap ?",
    allowGeoloc : "Geolocalisation :",
    email: "Email",
    country:"Pays",
    town: "Ville",
    zipCode: "Code postal",
    adress: "Adresse"
  },
  addPicture: {
    title: "Ajouter image",
  },
  fullScreenVideo: {
    title: "fullScreenVideo",
    confirm: "Le media a été enregistré dans votre librairie.",
    close: "Fermer",
  },
  videoScreen: {
    title: "Vidéo",
  },

  medias: {
    title: "Ajouter un média",
    saveToLibrary: "Ajouter dans la librairie",
    videos: "Vidéos",
    camera: "Photos",
    modify_profil: "Ajouter une image depuis ...",
    library: "Galerie",
    download: "Telecharger depuis :",
    takePicture: "Prendre une photo",
    takeVideo: "Prendre une vidéo",
    postVideo: "Poster la vidéo",
    got_Animal : "Vous êtes proprietaire d'un ou plusieurs animaux ...",
    noGot_Animal : "Vous cherchez à adopter ou vous êtes un professionnel animalier. Santé, Elevage, Associations, Refuges ...",
    share_Video :"Partager cette vidéo",
    videoProcessing : "Selon la qualité de votre connexion et le type de vidéo, le traitement peux prendre un peu de temps.",
    pleaseWait : "Traitement vidéo en cours, ... Patientez svp",

  },
  profiles: {
    title: "Vos profils",
    male: "Male",
    female: "Femelle",
    other: "Autre",
    localisation: "Localisation",
    adress: "Adresse",

  },
  addPost: {
    title: "Nouvelle publication",
    editPost: 'Edit Post',
    addLegend: 'Ajouter une legende ...',
    publish: "Partager",
    mediaTraitment: 'Traitement du média',
  },
  legends: {
    title: "Legendes",
  },

  signalment: {
    title: "Signalement",
  },
  addComment: {
    title: "Commentaires",
    answer: 'Répondre ...',
    addFollower : "Suivre",
    removeFollower: "Se désabonner",
    liked:"J'aime",
    delete: "Supprimer",
    commentary: "Commentaire(s)",
    addComments: "Ajouter",
    modify:"Modifier",
    publish:"Publier",
    response: "En réponse à ",
    tendancyResponse: "Réponses tendances",
  },
  loveSwap: {
    noMoreCards: "Il n'y a plus de cartes",
    like: "j'aime",
    noLike: "j'aime pas",
    yes: "Oui",
    no: "Non",
    loveMatch: "LoveMatch",
    likers: "Likers ",
    searchSwapDistance : "Choisissez la distance de recherche",
    all: "Tous les genres",
    allSpeciesSearch: "Toutes les espèces",
    allBreedsSearch: "Toutes les races",
    specifySearch: "Specifiez votre recherche :",
    loveNewSearch: "Nouvelle recherche",
    reproduction: "Reproduction",
    adoption: "Adoption",
    undo: "Retour",
    chooseSpecies: "Choisir l'espece",
    chooseBreeds: "Choisir la race",
    search: "Recherche"
  },
  premium: {
    title: "Compte Premium",
    activate: "Activer votre compte premium"
  },
  loveMatch: {
    title: "Vos Matchs",
    matches: "Matches",
    myLikers:"Vos likers",
    myLovers:"Vos Matchs",
  },
  loveLikers: {
    title: "Love Likers",
  },
  animalDetails: {
    title: "Animal details",
    posts: 'Posts',
    followers: 'Followers',
  },

  postList: {
    title: "Post List",
  },
  likerList: {
    title : "Liker List",
  },
  friendList: {
    title : "Friend List",
  },
  followerList: {
    title : "Follower List",
  },
  favoriteList: {
    title : "Favorite List",
  },
  bookmarksList: {
    title : "Bookmarks List",
  },

  modalSettings: {
    switchProfile: "Changer / Supprimer / Ajouter",
    profile: "Profile",
    addProfile: "Ajouter un profil",
    buddies: "Buddies",
    likes: "Likes",
    blockedMembers: "Membres bloqués",
    settings: "Settings",
    legals : "Legals",
    logOut: "Log_Out",
    geolocalisation: "Geolocalisation",
    activeGeolocalisation: "Activer la geolocalisation",
    notifications: "Notification",
    favorite: "Posts favoris",
    userSettings: "Reglages utilisateur",
    alert: "Alerte animal perdu, volé"
  },
  sharePost: {
    title: "Share Post",
  },
  sendPost: {
    title: "Partager un Post",
  },

  chatMessage: {
    title: "Chat Message",
  },
  chatRoom: {
    title: "Ajouter Message",
    yourMessage: "Votre message"
  },

  notifications: {
    title: "Notifications",
    AllowNotificationTxt: "Autoriser les notifications et recevoir des messages d'autres membres.",
    activeNotifications: 'Activer les notifications',
  },

  logOut:{
    title: "Deconnexion",
    seeYouSoon : "A bientôt ...",

  },
  legal:{
    title: "Engagement legal",

  },


  Medias : {
    SaveToLibrary: "Ajouter dans la librairie",
    Videos: "Vidéos",
    Camera: "Photos",
    Modify_profil: "Ajouter une image depuis ...",
    Library: "Galerie Médias",
    Download: "Telecharger depuis :",
    takepicture: "Prendre une photo",
    Takevideo: "Prendre une nouvelle vidéo",
    PostVideo: "Poster la vidéo",
    sendVideo: "Utiliser la vidéo",
    Got_Animal : "Vous êtes proprietaire d'un ou plusieurs animaux ...",
    NoGot_Animal : "Vous cherchez à adopter ou vous êtes un professionnel animalier. Santé, Elevage, Associations, Refuges ...",
    Share_Video :"Partager cette vidéo",
    VideoProcessing : "Selon la qualité de votre connexion et le type de vidéo, le traitement peux prendre un peu de temps.",
    PleaseWait : "Traitement vidéo en cours, ... Patientez svp",
},
messages : {

  deletedRoom: 'Cette discussion a été supprimée',
},


user : {
  searchAdopt: "Cherche à adopter :",
  noPosts: "Il n'y a pas de Posts",
  published: "Publications",
},

marker : {
  selectMarker : 'Choisissez un type de marker',
  update: 'Modifier',
  title: "Liste des markers",
  details: "Details du marker"
},
bloker: {
  title: "Profils bloqués",
  unblock: "Débloquer",
},
userSetting: {
  title: "Reglages Utilisateur",
  changeEmail: "Changer email",
  changePwd: "Changer le mot de passe",
  deleteAccount: "Supprimer le compte",
  isPremium: "Compte Premium",
  changeEmailTxt: "Afin de changer votre email, vous devez entrer votre mot de email. Vous aller recevoir un code qui vous sera necessaire pour changer votre adresse mail.",
  newAdress: "Nouvelle adresse email",
  confirmEmail: "Confirmer nouvel email",
  accountInformations: "Informations du compte",
  gender: "Votre genre",
  country: "Votre pays ?",
  search: "Rechercher",
  userUpdated: "Vos paramètres ont bien été modifiés.",
  actualEmail: "Email actuel",
  newEmail: "Nouvelle adresse email",
  confirmNewEmail: "Confirmer nouvelle adresse email",
  alreadyExist: "Cette adresse existe déja",
  error: "Erreur",
  newPwd:"Nouveau mot de passe",
  newPwdConfirm: "Confirmer nouveau mot de passe",
  

},
alert:{
  addPicture: "Ajouter des photos",
  title: "Alerte, demande d'aide",
  alertSubject: "Voulez vous activer l'alerte et voir sur le wall un menu deroulnt correspondnat a votre alerte dans les 20km ",

},
launchAlert:{
  title: "Renseignements",
  alertSubject: "Voulez vous activer l'alerte et voir sur le wall un menu deroulnt correspondnat a votre alerte dans les 20km ",
  alertPinPlace : "Pointez sur la carte l'endroit ou votre animal a disparu, a été volé, ou les zones à risque.\n",
  alertPinPCancel : "Annuler avec ",
  savePinAlert : "Enregistrez-le avec ",
  contact: "Contacter le propriétaire",
  informations: "Vous aller définir à partir d'un point central une zone d'alerte pour tous les utilisateurs de BuddyDiary.",
},
alertDetails: {
title: "Details de l'alerte",
lost: "Perdu",
stolen: "Volé",
hurted: "Blessé",
poisonned: "Empoisonné",
subject: "Vous êtes sur le point de lancer une alerte générale pour tous les utilisateurs de MyBuddy dans un rayon de 50km.\n\nRenseignez les champs suivants",
alertType: "Definir votre alerte pour",
textTooLong: "Vous avez dépassé la limite de texte.",
warning: "Attention",
addImage: "Ajouter des photos recentes",
maxAlert: "Vous avez dépassé le nombre d'alerte disponible. Passez en mode Premium pour ajouter d'autre alerte.",

},
alertList: {
title: "Vos alertes",



},





  Page : {
    Male: "Male",
    Female: "Femelle",
    Adoption: "Adoption",
    Active_Premium: "Vous devez activer votre compte Premium pour utiliser le Loveswap.",
    Nomore_Cards: "Il n'y a pas de profils correspondants à votre recherche. \n \n Voir les likers ? ",
    Health_Place : "Santé de mon animal",
    Alert_Lost: "Alert, J'ai perdu mon animal",
    Market_Place: "Market Place",
    My_Blokers: "Membres bloqués",
    My_Likes: "Mes likes",
    Download: "Télécharger",
    Downloading: "Chargement ...",
    Markerpin_1 : "Placez votre marker sur la carte. Annuler avec ",
    Markerpin_2 : "Enregistrez-le avec ",
    Other_Animals: "Autre animaux",
    All_Animals: "Tous les animaux",
    Answer : "Répondre",
    Animal_Create_Profile : "Nouveau profil",
    Visitor_Create_Profile : "Profil",
    Mentions_Legals: "Mentions Legales",
    Member_Date : "Membre depuis le",
    Premium_Member_Date : "Membre Premium depuis le",
    Block_Member : "Bloquer",
    Member_No : "Ce profil a été supprimé",
    Subscriptions : "Buddies",
    Blokers : "Membres bloqués",
    My_Subscriptions : "Mes buddies",
    Subscribers : "Buddies",
    Abonned: "Abonnés",
    NoLoveLikerList: "Profils non selectionnés",
    Marker_Detail:"Marker",
    Marker_List:"Liste des markers",
    Add_Friends:"Ajouter comme buddy's",
    Delete_Friend:"Supprimer",
    Day: "Jour",
    Month: "Mois",
    Year: "Année",
    General_settings: "Réglages",
    Legends: "Legendes",
    Loading: "Chargement ...",
    Posts: "Posts",
    Followers: "Abonnés",
    Follow: "Follow",
    Store : "Enseignes",
    Health: "Santé",
    Services: "Services",
    Outdoor: "Exterieur",
    Comments: "Commentaires",
    Add_Comments:"Ajouter Commentaire",
    Answer_Comments : "Répondre ..." ,
    Commentary:"Commentaire(s)",
    Add_Commentary:"Commentaires",
    Add_Message:"Envoi Message",
    Add_Typeof : "Ajout Espece",
    Add_Breed_Txt: "Vous pouvez ajouter une race + si celle ci n'est pas presente la liste ...",
    Publish:"Publier",
    Modify:"Modifier",
    Member_Since : "Membre depuis le",
    Liked:"J'aime",
    Liked_by:"Aimé par",
    Animal_Details:"Identité",
    Animals_Map:"Carte",
    Swap_Fiancy:"Love swap",
    Alert_Lost :"Alert : J'ai perdu mon animal",
    Seefriends :"Abonnés",
    SeePostfriends :"Amis",
    SeeLegends :"Icones legendes",
    Signalment :"Signalement",
    Marker_Signalment :"Marker Signalement",
    My_Friends : "Mes buddy's",
    Post_Likers : "Likers",
    Settings : "Reglages",
    AnimalsMap : "Animals Carte",
    Next : "Suivant",
    Validate : "Valider",
    Add: "Ajouter",
    Animal_Profile : "Modifier profil",
    BreedScreen : "Race",
    Add_Animal :"Ajouter Animal",
    Create_New_Animal : "Ajouter un animal",
    List_Animal : "Profils",
    Create_Profil : "Créer profil",
    Add_BreedScreen : "Ajouter nouvelle race",
    Add_BreedScreenTxt : "Ajoutez la race de votre animal ...",
    SpeciesScreen : "Espece",
    Choose_Town : "Votre ville",
    Privatie: "Privé",
    Age : "ans",
    No_Profil : "Completez le profil ...",
    Account: "Compte",
    Delete_Account: "Supprimer mon compte",
    Delete_Account_Txt : "Tous vos messages et informations seront définitivement supprimés...",
    Accept_Legals : "Vous reconnaissez avoir lu et accepté notre politique de confidentialité",
    Delete: "Supprimer",
    Just_Now: "A l'instant ...",
    Your_Account: "Votre Compte",
    Choose_Profil : "Choisir le profil",
    Choose_Typeof : "Choisir l'espece",
    Change_Profil : "Changer de profil",
    See_Profile : "Voir le profil",
    User_Profile: "Votre Profil",
    Password:"Password",
    Soon_Available: "Bientot ...",
    LoveMessage:"Messages",
    Publicity: "Publicité",
    Notifications: "Notifications",
    Premium_Status: "Compte Premium",
    Geolocalisation: "Geolocalisation",
    Log_Out: "Deconnexion",
    SeeYouSoon : "A bientôt ...",
    Send: "Envoi",
    Placeholder_Youressage: "Votre message ...",
    Chat_Screen: "Chat Screen",
    Profile : "Profil",
    New_Profile : "Nouveau profil",
    Add_Profile : "Ajouter profil",
    Switch_Profile : "Changer / supprimer profil",
    Your_Text : "Votre texte ...",
    Years : "Ans",
    Weight : "Poids",
    Height : "Taille",
    Dynamic : "Dynamique",
    Chat_Screen_ShareMessg: "Partager un post",
    Player : "Joueur",
    Sociability : "Sociabilité",
    Lof : "Lof",
    Type_Of_Food : "Nourriture",
    Type_Of_Home : "Habitat",
    Want_Childs : "Reproduction",
    Published : "Publications",
    Friends : "Amis",
    Yes : "Oui",
    No : "Non",
    Send_Message : "Envoi message",
    Message : "Message",
    Add_Friends : "Ajouter amis",
    Allow_Geoloc : "Active localisation",
    Allow_Notifs : "Active notifications",
    Is_localisation_Datas : "Localisation coordonées",
    Allow_Loveswap : "LoveSwap",
    Legals : "Legals",
    Informations: "Informations",
    Your_Profile: "Votre profil",
    Confidentiality: "Confidentialité",
    Security:"Securité",
    Premium_Acces:"Compte Premium",
    Discussions:"Discussions",
    Adddiscussions: "Ajouter Discussions",
    Newdiscussions: "Nouvelle Discussion",
    Discussions_Post:"Partager le post",
    LoveSwap: "LoveSwap",
    AllowNotificationTxt: "Autoriser les notifications et recevoir des messages d'autres membres.",
    PremiumIntroTxt: "L’abonnement Premium permet d’accéder à l’intégralité des fonctionnalités de l’application. \n \n Le loveSwap, pour chercher des profils de reproduction ou d’adoption par espèce, race ou genre. \n \n Le Market Place pour vendre des objets ou accessoires déjà utilisés.",
    AllowGeolocalisationTxt: "Souhaitez vous beneficier de la géolocalisation et apparaitre sur la carte. La position de votre animal est volontairement modifée dans un rayon de 2km afin de preserver votre anonymat. Vous pouvez a tout moment desenclencher la géolocalisation.",
    AddAvatarpic : "Galerie images",
    MediasScreen : "Ajouter Medias",
    Likes: "Likes",
    GetLocalisation : "Patientez ... Récuperation de vos coordonnées ...",
    Matches: "Matches",
    LoveLikers:"Mes Likers",
    Likers:"Likers",
    Lovers:"Lovers",
    Swap_Settings: "Reglages",
    Swap_Settings_txt: "Modifiez les champs de recherche :",
   
    Choose_Genre : "Selectionnez le genre",
    Search_All_Genre : "Cherchez tous les genres",
    Choose_Breed_ : "Selectionnez la race ...",
    //Choose_Typeof : "Quel est votre animal ?",
    Choose_Breed : "Selectionnez la race",
    Choose_Marker : "Recherche ...",
    Search : "Recherche ...",
    Search_All :"Nom, Espece, Race, Genre ...",
    Add_Breed : "Ajouter votre race dans la liste",
    Choose_Species : "Choisissez le type d'animal dans votre recherche",
    UpdatePost: "Modifier",
    Messages: "Messages",
    Share_Post :"Nouvelle Discussion",
    SharePost: "Partager le post",
    Sex_Signalment: "Contenu a caractere sexuel",
    Hate_Signalment: "Discours ou symbole haineux",
    Violence_Signalment: "Violence ou organisation haineuse",
    Harrasment_Signalment: "Intimidation et harcèlement",
    Illegal_Signalment: "Contenu illegal",
    Fake_Signalment: "Fausses informations",
    Why_Marker_Signalment : "Pourquoi signalez vous ce marker ?",
    Signalment_Details : "Choisissez le motif du signalement. Un message sera envoyé à la modération et celui ci sera effacé si le contenu ne réponds pas à notre charte éthique.",
    MediasPolicy: "Ajouter des images pour le profil de votre animal",
    Signalment_AlreadySend : "Vous avez déja transmis un signalement",
    Signalment_Send : "Votre signalement a été transmis",
    Why_Signalment : "Pourquoi signalez vous ce post ?",
    Add_Follower : "Suivre",
    Re_Activate : "Reactiver ce profil",
    No_Profils: "Il n'y a pas de profils",
    Remote_Follower: "Se désabonner",
    Reproduction: "Reproduction",
    Author : "Auteur",
    Discuss_Creation: "Discussion crée le",

    


},
  Modal : {
    Modify_Post: "Modifier post",
    Delete_Post: "Supprimer",
    Delete_Confirmation: "Effacer Confirmation",
    Delete_Message: "Attention : Effacer est permanent !",
    Warning : "Confirmation",
    confirmation: "Confirmation",
    birthdayTitle: "Attention",
    Delete: "Supprimer",
    Modify: "Modifier",
    Cancel: "Annuler",
    Share: "Partager",
    Select: "Selectionnez ...",
    Ok: "OK",
    Empty_Fields : "Champs vide !",
    Signal: "Signaler",
    Block: "Bloquer",
    understand: "J'ai compris",
    WarningDeleteAccount: "Voulez vous supprimer votre compte ?",
    WarningDeleteAccountTxt: "Vous aller supprimer defintivement tous les profils associés.",
    WarningBlokerTitle: "Voulez vous bloquer ce profil ?",
    WarningBlokerMessage: "Voulez vous bloquer cet utilisateur ? \n\n Les profils associés n'apparaitront plus dans votre fil d'actus et dans vos recherches. Vous pouvez à tout moment le debloquer dans vos paramètres.",
    Warning_comment_message: "Voulez vous supprimer ce post ?",
    warningDeleteMarker: "Voulez vous supprimer ce marker ?",
    warningDeleteAlert: "Voulez vous supprimer cette alerte ?",

    warningDeleteLove: "Voulez vous supprimer ce liker ?",
    warningDeleteLover: "Voulez vous supprimer ce lover ?",
    warningDeleteProfile: "Voulez vous supprimer ce profil ?",
    warningBirthday: "Voulez ne pouvez malheureusement pas vous inscrire, votre date de naissance est en dessous de l'age requis pour cette application.",
    Warning_Delete_Account: "Voulez vous supprimer definitvement votre compte ? Vos profils, images, posts, messages, commentaires, etc ... seront definitivement supprimés.",
    Warning_Block_Member:"Voulez vous bloquer ce membre ?",
    Warning_Block_Member2:"Vous ne verrez plus son profil et ses activitées. Le membre ne verra plus votre profil ni vos activitées.",
    Warning_Breed_Already_Exist: "Cette race existe déjà !",
    Warning_Delete_Pic: "Voulez vous supprimer cette image ?",
    Warning_Delete_Message: "Voulez vous supprimer ce message ?",
    Warning_Delete_Lover: "Voulez vous supprimer ce Match ?",
    Warning_Delete_Liker: "Voulez vous supprimer ce Liker ?",
    Warning_Download: "Voulez vous téléchager cette image ?",
    Warning_DownloadVideo: "Voulez vous téléchager cette vidéo ?",
    Warning_DownloadVideo: "Voulez vous téléchager cette vidéo ?",
    WelcomeModal: "Bienvenue",
    WelcomeGo: "C'est parti ..",
    WelcomeTextStars: "Particuliers, Associations, Professionnels du monde animalier, vous trouverez ici les moyens de communiquer sur votre, ou vos animaux, échanger des astuces ou bonnes adresse avec d’autres propriétaires.\n\nVous pourrez dans un cadre d’élevage ou de reproduction, rechercher le ou la partenaire idéal près de chez vous. Rechercher par espèce et par race. Visualiser les autres animaux aux alentours, les points d’intérêts géographique ou les alertes de perte, vol, ou empoisonnement déposées par d’autres propriétaires.\n\nDevelopper un réseau d’amis et d’entraide pour nos petits compagnons.",
    WelcomeModalInfos: "Vous pouvez créer un ou plusieurs profils, échanger avec d’autres propriétaires les bons plans, les conseils, les trucs et astuces. Trouver un éleveur, un professionel ou encore un service animalier. Et rencontrer d’autres animaux près de chez vous.",
    Welcome_Title: "Bienvenue sur MyBuddyDiary",
    Welcome_Text: "Vous pouvez créer un ou plusieurs profils, échanger avec d’autres propriétaires les bons plans, les conseils, les trucs et astuces. Trouver un éleveur, un professionel ou encore un service animalier. Et rencontrer d’autres animaux près de chez vous.",
    Welcome_AnimalMiss : " Mais tout d'abord, vous devez créer un profil, choisissez ...",
    Valid :  "OK",
    Create_Profil :  "Creer le profil",
    Agreed : "Accepter",
    Posts_Politics_Title: "Règles de bonne conduite",
    Posts_Politics_Text: "Conformément à la charte d’utilisation de MyBuddyDiary, nous vous demandons de modérer vos propos lors de vos posts. Sexualité, vulgarité, prosélitisme, incitations sous n’importe quelles formes sont interdite. Vos images et écrits doivent rester courtois et bienveillants. Vous vous engagez à respecter la charte de bonne conduite énoncée ci dessus.",
    Posts_Politics_DeleteAccount: "En cas de non respect des instructions, le post sera supprimé.",
    Marker_Details : "Description",
    Marker_Details_Typeof: "Definissez le type de marker",
    Marker_Details_Title : "Titre",
    Marker_Details_Description : "Description",
    Marker_Details_DescriptionLimite : "400 Char. max",
    Marker_Details_Adress : "Adresse",
    Marker_Details_Save : "Enregistrer",
    Marker_Add : "Ajouter marker",
    Alert: "Alert",
    Like_Post : "Liker ce post",
    UnLike_Post : "Unliker ce post",
    Add_Comment : "Ajouter un commentaire",

},
Form : {
  dog: "Chien",
  Username: "Pseudo",
  Password: "Password",
  Password_Conf: "Password Confirmation",
  Login: "Login",
  Create_Account: "Creer compte",
  Forgot_Password: "Oublie du password",
  Activation_Code: "Vous avez votre code d'activation",
  Already_Registered: "Déjà enregistré",
  Caption_Password: "* Doit contenir :",
  Symbols: "caracteres",
  Fname: "Prénom",
  Lname: "Nom",
  Email: "Email",
  Confirmation: "Confirmation",
  Confirm_Email: "Confirmation email",
  Submit: "Envoi",
  Geolocalisation: "Geolocalisation",
  PremiumPayLabel: "Activer le compte Premium",
  AllowGeolocalisation: "Autorise la géolocalisation",
  SetNewGeolocalisation: "Définir une nouvelle géolocalisation",
  AllowNotification: "Autorise les notifications",
  Allow_Loveswap : "Visible dans le LoveSwap",
  MatchInternationale: "Limiter la distance de recherche",
  Adress: "Adresse",
  Street: "Rue",
  StreetNumber: "Numéro",
  Town: "Ville",
  Zip: "Code Postal",
  Country: "Pays",
  Private_Profile : "Mode privé",
  New_Notifications: "Notifications",
  Current_Pwd : "Password actuel",
  New_Pwd : "Nouveau Password",
  Add_Description : "Ajouter une description ...",
  Cancel: "Annuler",
  Delete: "Supprimer",
  Unblock: "Débloquer",
  Type_Of: "Espece",
  Breed: "Race",
  Obligatory: "* Obligatoire",
  Genre: "Genre",
  Sterilisation: "Sterilisation ?",
  Date_Birth: "Date naissance",
  Lof: "L.O.F (Documents)",
  Small: "Petit",
  Average: "Moyen",
  Big: "Grand",
  Yes: "Oui",
  No: "Non",
  Alittle: "Un peu",
  Heavy : "Lourd",
  Light: "Leger",
  Sex_Partner : "Reproduction",
  SearchAllSpecies : "Chercher toutes les especes",
  SearchAllBreeds : "Chercher toutes les races",
  Adoption: "Je suis à adopter",
  User_Adoption: "Je cherche à adopter un animal",
  Animal_Adoption: "Je suis à adopter",
  User_identification : "Pseudo, Nom, Société",
  Download: "Télécharger",
  

},

Error : {
  NoPost : "Il n'y a pas de posts",
  No_Comments : "Il n'y a pas de commentaires",
  No_Favorites : "Il n'y a pas de favoris ...",
  No_Friends : "Il n'y a pas de buddy's... Abonnez vous a des animaux pour voir leur posts et discuter avec eux.",
  No_Blokers : "Il n'y a pas de membres bloqués ...",
  NoLikers : "Il n'y a pas de likes ...",
  No_LoveLikers : "Il n'y a pas de likers ...",
  No_Lovers : "Il n'y a pas de lovers ...",
  No_Matches : "Il n'y a pas de matches ...",
  No_ActionPost : "Pas de posts ...",
  No_Notifications : "Il n'y a pas de notifications ...",
  No_Discussions : "Il n'y a pas encore de discussions. Suivez les animaux pour discuter avec eux. Ajoutez d'autres discussions avec le + ",
  Bad_Fields: "Certains champs sont vides ...",
  NoMessages : "Il n'y a pas de messages ...",
  NoAlert : "Il n'y a pas d'alertes ...",
  Empty_Required_fields: "Les champs requis sont vides ...",
  No_Markers : "Il n'y a pas de Markers ...",
  No_Animal: "Il n'y a pas de profil ...",
  NoFollowers: "Il n'y a pas d'abonnés ...",
  No_Subscribers: "Il n'y a pas de buddy's ...",
  No_Bookmarks: "Il n'y a pas de bookmarks ...",
  Email_Alreadyexist: "L'email existe déja ...",
  Email_Notexist: "L'email n'existe pas ...",
  wrongdata : 'Les données sont incorrectes ...',
  Email_Novalid: "Email non valide ...",
  Timme_Upgrade: "Il est temps de faire une mise à jour ...",
  Unvalid_App_Version: "Votre version n'est plus compatible. La mise à jour est necessaire pour que l'application puisse fonctionner correctement.",


  

},

Animal : {
  Dog: "Chien",
  Cat: "Chat",
  Rabbit: "Lapin",
  Fish: "Poisson",
  Bird: "Oiseaux",
  Bug: "Insecte",
  Horse: "Chevaux",
  Mouse: "Souris",
  Reptile: "Reptile",
  Hamster: "Hamster",
  Ferret: "Furet",
  Spider: "Araignée",
  Femelle_Off: "Femelle sterilisée",
  Femelle_On: "Femelle non sterilisée",
  Male_Off: "Male sterilisé",
  Male_On: "Male non non sterilisée",
  Lof: "Pure Race",
  Wantbaby: "Oui pour la reproduction",
  Cow: "Vache",
  Goat: "Chèvre",
  Snake: "Serpent",
  Pig: "Cochon",
  Turtle: "Tortue",
  Heart: "Cherche une adoption",
  Bull: "Taureau",
  Sheep: "Mouton",
},
};